cluster_config:
  racks:
    # High-Performance Computing Rack
    - id: "rack0"
      name: "High-Performance Computing Rack"
      machines:
        - id: "rack0_machine_0"
          cpu_memory: 1024000  # 1TB
          gpus:
            - model: "H100_80GB"
              count: 8
        - id: "rack0_machine_1"
          cpu_memory: 1024000  # 1TB
          gpus:
            - model: "H100_80GB"
              count: 8
        - id: "rack0_machine_2"
          cpu_memory: 512000  # 512GB
          gpus:
            - model: "A100_80GB"
              count: 8
        - id: "rack0_machine_3"
          cpu_memory: 512000  # 512GB
          gpus:
            - model: "A100_80GB"
              count: 8

    # Mixed Workload Rack
    - id: "rack1"
      name: "Mixed Workload Rack"
      machines:
        - id: "rack1_machine_0"
          cpu_memory: 512000  # 512GB
          gpus:
            - model: "A100_80GB"
              count: 4
            - model: "T4"
              count: 2
        - id: "rack1_machine_1"
          cpu_memory: 512000  # 512GB
          gpus:
            - model: "A100_80GB"
              count: 4
            - model: "T4"
              count: 2
        - id: "rack1_machine_2"
          cpu_memory: 256000  # 256GB
          gpus:
            - model: "A100_40GB"
              count: 4
        - id: "rack1_machine_3"
          cpu_memory: 256000  # 256GB
          gpus:
            - model: "A100_40GB"
              count: 4

    # Development and Testing Rack
    - id: "rack2"
      name: "Development and Testing Rack"
      machines:
        - id: "rack2_machine_0"
          cpu_memory: 256000  # 256GB
          gpus:
            - model: "A100_40GB"
              count: 2
            - model: "T4"
              count: 2
        - id: "rack2_machine_1"
          cpu_memory: 256000  # 256GB
          gpus:
            - model: "A100_40GB"
              count: 2
            - model: "T4"
              count: 2
        - id: "rack2_machine_2"
          cpu_memory: 128000  # 128GB
          gpus:
            - model: "T4"
              count: 4
        - id: "rack2_machine_3"
          cpu_memory: 128000  # 128GB
          gpus:
            - model: "T4"
              count: 4

    # Inference Rack
    - id: "rack3"
      name: "Inference Rack"
      machines:
        - id: "rack3_machine_0"
          cpu_memory: 128000  # 128GB
          gpus:
            - model: "T4"
              count: 8
        - id: "rack3_machine_1"
          cpu_memory: 128000  # 128GB
          gpus:
            - model: "T4"
              count: 8
        - id: "rack3_machine_2"
          cpu_memory: 128000  # 128GB
          gpus:
            - model: "T4"
              count: 8
        - id: "rack3_machine_3"
          cpu_memory: 128000  # 128GB
          gpus:
            - model: "T4"
              count: 8